"use server";
import { revalidatePath } from "next/cache";
import { requireAdminOrEditor } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { isUuid, normalizeSlug, publicationValues, validatePostInput, type PostInput } from "@/lib/blog/cms-validation";

export type ActionResult = { ok:boolean; message:string; id?:string; errors?:Record<string,string> };
async function context(){ const user=await requireAdminOrEditor(); return {user,db:await createClient()}; }
export async function savePost(id:string|null,input:PostInput):Promise<ActionResult>{ const {user,db}=await context(); if(id && !isUuid(id)) return {ok:false,message:"Invalid article."}; input={...input,title:input.title.trim(),slug:normalizeSlug(input.slug),excerpt:input.excerpt.trim(),seo_title:input.seo_title?.trim()||null,seo_description:input.seo_description?.trim()||null}; const errors=validatePostInput(input); if(Object.keys(errors).length) return {ok:false,message:"Please correct the highlighted fields.",errors}; const {data:duplicate}=await db.from("posts").select("id").eq("slug",input.slug).neq("id",id||"00000000-0000-0000-0000-000000000000").maybeSingle(); if(duplicate) return {ok:false,message:"That slug is already in use.",errors:{slug:"Choose a unique slug."}}; if(input.category_id){const {data}=await db.from("categories").select("id").eq("id",input.category_id).maybeSingle();if(!data)return {ok:false,message:"The selected category no longer exists."};} if(input.tag_ids.length){const {data}=await db.from("tags").select("id").in("id",input.tag_ids);if(data?.length!==new Set(input.tag_ids).size)return {ok:false,message:"One or more selected tags no longer exist."};} let currentPublished:string|null=null;let currentSlug:string|null=null;if(id){const {data}=await db.from("posts").select("published_at,slug").eq("id",id).single();currentPublished=data?.published_at??null;currentSlug=data?.slug??null;} const row={title:input.title,slug:input.slug,excerpt:input.excerpt,content:input.content,featured_image_path:input.featured_image_path,featured_image_alt:input.featured_image_alt,category_id:input.category_id,status:input.status,seo_title:input.seo_title,seo_description:input.seo_description,published_at:publicationValues(currentPublished,input.status,input.published_at),author_id:user.id}; const result=id?await db.from("posts").update(row).eq("id",id).select("id").single():await db.from("posts").insert(row).select("id").single(); if(result.error)return {ok:false,message:result.error.code==="23505"?"That slug is already in use.":"The article could not be saved."}; const postId=result.data.id; await db.from("post_tags").delete().eq("post_id",postId); if(input.tag_ids.length){const {error}=await db.from("post_tags").insert(input.tag_ids.map(tag_id=>({post_id:postId,tag_id})));if(error)return {ok:false,message:"Article saved, but tags could not be updated."};} revalidatePath("/admin");revalidatePath("/admin/blogs");revalidatePath("/blog");revalidatePath(`/blog/${input.slug}`);if(currentSlug&&currentSlug!==input.slug)revalidatePath(`/blog/${currentSlug}`);revalidatePath("/sitemap.xml");return {ok:true,id:postId,message:input.status==="published"?"Article published.":input.status==="archived"?"Article archived.":"Draft saved."}; }
export async function changePostStatus(id:string,status:PostInput["status"]){if(!isUuid(id))return {ok:false,message:"Invalid article."};const {db}=await context();const published_at=status==="published"?new Date().toISOString():null;const {data,error}=await db.from("posts").update({status,published_at}).eq("id",id).select("slug").single();revalidatePath("/admin");revalidatePath("/admin/blogs");revalidatePath("/blog");if(data?.slug)revalidatePath(`/blog/${data.slug}`);revalidatePath("/sitemap.xml");return {ok:!error,message:error?"Status could not be changed.":"Status updated."};}
export async function saveTaxonomy(kind:"categories"|"tags",id:string|null,name:string,slugValue:string,description?:string){const {db}=await context();const slug=normalizeSlug(slugValue);if(name.trim().length<(kind==="tags"?1:2)||!slug)return {ok:false,message:"Enter a valid name and slug."};if(id&&!isUuid(id))return {ok:false,message:"Invalid item."};let error;if(kind==="categories"){const row={name:name.trim(),slug,description:description?.trim()||null};({error}=id?await db.from("categories").update(row).eq("id",id):await db.from("categories").insert(row));}else{const row={name:name.trim(),slug};({error}=id?await db.from("tags").update(row).eq("id",id):await db.from("tags").insert(row));}revalidatePath(`/admin/${kind}`);return {ok:!error,message:error?.code==="23505"?"That slug already exists.":error?"Could not save changes.":"Saved."};}
export async function deleteTaxonomy(kind:"categories"|"tags",id:string){if(!isUuid(id))return {ok:false,message:"Invalid item."};const {db}=await context();if(kind==="categories"){const {count}=await db.from("posts").select("id",{count:"exact",head:true}).eq("category_id",id);if(count)return {ok:false,message:`This category is used by ${count} article(s). Removing it would uncategorize them; edit those posts first.`};}const {error}=await db.from(kind).delete().eq("id",id);revalidatePath(`/admin/${kind}`);return {ok:!error,message:error?"Could not delete this item.":"Deleted."};}
