import type { Json } from "@/lib/supabase/database.types";
import { isEditorDocument, isPostStatus, isValidBlogSlug } from "./validation.ts";

export const IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/avif"] as const;
export const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
export function normalizeSlug(value: string) { return value.toLowerCase().trim().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 200).replace(/-+$/g, ""); }
export function isUuid(value: unknown): value is string { return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
export function validateImage(file: { type: string; size: number }) { if (!IMAGE_TYPES.includes(file.type as never)) return "Use a JPEG, PNG, WebP, or AVIF image."; if (file.size > MAX_IMAGE_BYTES) return "Image must be 5 MB or smaller."; return null; }
export type PostInput = { title:string; slug:string; excerpt:string; content:Json; featured_image_path:string|null; featured_image_alt:string|null; category_id:string|null; tag_ids:string[]; seo_title:string|null; seo_description:string|null; status:"draft"|"published"|"archived"; published_at:string|null };
export function validatePostInput(input: PostInput) { const errors: Record<string,string> = {}; if (input.title.trim().length < 2 || input.title.length > 200) errors.title="Use 2–200 characters."; if (!isValidBlogSlug(input.slug)) errors.slug="Use lowercase letters, numbers, and hyphens."; if (input.excerpt.trim().length < 10 || input.excerpt.length > 500) errors.excerpt="Use 10–500 characters."; if (!isEditorDocument(input.content)) errors.content="Article content is invalid."; if (!isPostStatus(input.status)) errors.status="Choose a valid status."; if (input.category_id && !isUuid(input.category_id)) errors.category_id="Choose a valid category."; if (input.tag_ids.some((id)=>!isUuid(id))) errors.tag_ids="Choose valid tags."; if (input.seo_title && input.seo_title.length > 70) errors.seo_title="SEO title must be 70 characters or fewer."; if (input.seo_description && input.seo_description.length > 170) errors.seo_description="SEO description must be 170 characters or fewer."; if (input.featured_image_path && (!input.featured_image_alt || input.featured_image_alt.trim().length < 2)) errors.featured_image_alt="Describe the featured image."; return errors; }
export function publicationValues(current: string | null, next: PostInput["status"], requested: string | null) { if (next === "published") return requested || current || new Date().toISOString(); return next === "draft" || next === "archived" ? null : current; }
