"use client";
import { useEditor, EditorContent } from "@tiptap/react";
import type { Content } from "@tiptap/core";
import StarterKit from "@tiptap/starter-kit";
import TextAlign from "@tiptap/extension-text-align";
import type { Json } from "@/lib/supabase/database.types";
export function RichTextEditor({ value, onChange }: { value: Json; onChange: (v: Json) => void }) {
  const editor = useEditor({ immediatelyRender: false, editorProps: { attributes: { "aria-label": "Article content" } }, extensions: [StarterKit.configure({ link: { openOnClick: false, HTMLAttributes: { rel: "noopener noreferrer nofollow" } } }), TextAlign.configure({ types: ["heading", "paragraph"] })], content: value as Content, onUpdate: ({ editor }) => onChange(editor.getJSON() as Json) });
  if (!editor) return <div className="h-48 animate-pulse rounded-xl bg-slate-100" />;
  const b = (label: string, active: boolean, run: () => void) => <button type="button" onClick={run} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${active ? "bg-emerald-700 text-white" : "bg-white text-slate-700 hover:bg-slate-100"}`}>{label}</button>;
  return <div className="overflow-hidden rounded-xl border border-slate-300 bg-white"><div className="flex flex-wrap gap-1 border-b bg-slate-50 p-2">{b("P", editor.isActive("paragraph"), () => editor.chain().focus().setParagraph().run())}{b("H2", editor.isActive("heading", { level: 2 }), () => editor.chain().focus().toggleHeading({ level: 2 }).run())}{b("H3", editor.isActive("heading", { level: 3 }), () => editor.chain().focus().toggleHeading({ level: 3 }).run())}{b("Bold", editor.isActive("bold"), () => editor.chain().focus().toggleBold().run())}{b("Italic", editor.isActive("italic"), () => editor.chain().focus().toggleItalic().run())}{b("Underline", editor.isActive("underline"), () => editor.chain().focus().toggleUnderline().run())}{b("Bullets", editor.isActive("bulletList"), () => editor.chain().focus().toggleBulletList().run())}{b("Numbers", editor.isActive("orderedList"), () => editor.chain().focus().toggleOrderedList().run())}{b("Quote", editor.isActive("blockquote"), () => editor.chain().focus().toggleBlockquote().run())}{b("Link", editor.isActive("link"), () => { const href = window.prompt("Link URL", editor.getAttributes("link").href || "https://"); if (href) editor.chain().focus().extendMarkRange("link").setLink({ href }).run(); })}{b("Rule", false, () => editor.chain().focus().setHorizontalRule().run())}{b("Left", editor.isActive({ textAlign: "left" }), () => editor.chain().focus().setTextAlign("left").run())}{b("Center", editor.isActive({ textAlign: "center" }), () => editor.chain().focus().setTextAlign("center").run())}{b("Undo", false, () => editor.chain().focus().undo().run())}{b("Redo", false, () => editor.chain().focus().redo().run())}</div><EditorContent editor={editor} className="cms-editor min-h-72 p-4" /></div>;
}
